apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: portfolio
      app.kubernetes.io/part-of: portfolio-jesuspb
    includeSelectors: false
    includeTemplates: true
